library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
library work;

--Project: Digital thermometer using LM75 sensor and 7-segment display.

--Details:
--1. "Active low" reset and 7-segment display
--2. 50MHz system clock, 100kHz I2C clock (generated by the PLL)
--3. The design is divided into different parts:
--	  a. ROM  
--   b. Decimal to BCD converter
--   c. I2C reader
--   d. Shift register and counters
--   e. Other combinational logic

entity digital_thermometer is
	port(rst_n: in std_logic;
		  clk: in std_logic;
		  --I2C signals for LM75
		  sda: inout std_logic;
		  scl: out std_logic;
		  --Signals for 7-segment display
		  dp: out std_logic;
		  seg: out std_logic_vector(6 downto 0);
		  sel: out std_logic_vector(3 downto 0));
end digital_thermometer;

architecture digital_thermometer_rtl of digital_thermometer is
begin
	
	display: entity work.seg_display(seg_display_rtl)
	port map(rst_n => rst_n, clk => clk, bcd => "000010000011", fp => '1',
				dp => dp, seg => seg, sel => sel);
				
end digital_thermometer_rtl;
